[package]
name = "pg_interval"
version = "0.4.2"
edition = "2018"
authors = ["Ryan Piper <piper.ryan235@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL interval type"
repository = "https://github.com/piperRyan/rust-postgres-interval"
readme = "README.md"
keywords = ["database", "postgres", "postgresql", "sql", "interval"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]
categories = ["date-and-time"]

[features]
default = ["postgres"]
postgres = ["postgres-types"]
serde = [
    "dep:serde",
    "serde/derive"
]
rkyv = [
    "dep:rkyv",
    "rkyv/size_32",
]
rkyv-validation = ["rkyv?/validation"]

[dependencies.rkyv]
version = "0.7.42"
optional = true
default-features = false


[dependencies.serde]
version = "1.0.137"
optional = true
default-features = false

[dependencies]
chrono = { version = "^0.4" }
bytes = { version = "^1" }
postgres-types = { version = "^0.2", optional = true }
